services:
  db:
    image: postgres:16-alpine
    container_name: colortheme-postgres
    ports:
      - "5433:5432" # expose on localhost:5433 to avoid conflicts
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: colortheme
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  db_data:
